/********************************************************************************
** Form generated from reading UI file 'trade_winner.ui'
**
** Created by: Qt User Interface Compiler version 5.2.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_TRADE_WINNER_H
#define UI_TRADE_WINNER_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTimeEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_TradeWinnerClass
{
public:
    QAction *actionClose;
    QAction *actionRestart;
    QAction *actionStopAllTask;
    QAction *actionOpenCalcWin;
    QWidget *centralWidget;
    QTabWidget *tabwid_holder;
    QWidget *tab_task_list;
    QTableView *tbview_tasks;
    QWidget *tab_buytask;
    QLabel *label_buytask_alert_price;
    QLabel *label_buytask_stock;
    QDoubleSpinBox *dbspbox_buytask_alert_percent;
    QComboBox *combox_buy_type;
    QDoubleSpinBox *dbspbox_buytask_alert_price;
    QLineEdit *le_buytask_stock;
    QLabel *label_buytask_show_pic;
    QPushButton *pbtn_add_buytask;
    QWidget *wid_bt_retreat;
    QCheckBox *cb_bt_back_alert_trigger;
    QDoubleSpinBox *spinBox_bt_retreat;
    QLabel *label_retreat_bfh_2;
    QLabel *label_bt_retreat;
    QWidget *wid_bt_step_range;
    QLabel *label_bt_step_range;
    QDoubleSpinBox *dbspbox_bt_step_range;
    QLabel *step_range_bfh_2;
    QLabel *label_bt_times;
    QSpinBox *spinBox_buytask_times;
    QWidget *wid_bt_mid_line;
    QLabel *lab_buytask_quantity;
    QLabel *label_buytask_total_num;
    QComboBox *combox_bt_price_level;
    QLabel *label_buytask_monitor_time;
    QLabel *label_price_level_2;
    QLabel *label_21;
    QTimeEdit *timeEdit_buytask_begin;
    QTimeEdit *timeEdit_buytask_end;
    QLabel *label_continue_time_2;
    QSpinBox *spinBox_buytask_continue_time;
    QLabel *label_22;
    QSpinBox *spinBox_buytask_quantity;
    QLabel *label_19;
    QPushButton *pbtn_buytask_all_quantity;
    QCheckBox *cb_buytask_chase_limitup;
    QLabel *label_alert_bfh_2;
    QWidget *tab_sell_task;
    QWidget *wid_ticker;
    QLabel *lab_out_sell2;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *lab_out_buy1;
    QLabel *label;
    QLabel *label_3;
    QLabel *label_2;
    QLabel *lab_out_buy3;
    QLabel *lab_out_buy5;
    QLabel *lab_out_sell4;
    QLabel *label_7;
    QLabel *label_11;
    QLabel *lab_out_sell1;
    QLabel *lab_out_sell3;
    QLabel *lab_out_buy4;
    QLabel *lab_out_sell5;
    QLabel *label_10;
    QLabel *lab_out_buy2;
    QLabel *label_8;
    QLabel *label_9;
    QWidget *wid_retreat;
    QCheckBox *cb_back_alert_trigger;
    QDoubleSpinBox *spinBox_retreat;
    QLabel *label_retreat_bfh;
    QLabel *label_retreat;
    QComboBox *combox_sell_type;
    QPushButton *pbtn_add_task;
    QDoubleSpinBox *dbspbox_alert_percent;
    QLabel *label_stock;
    QLabel *label_alert_price;
    QLineEdit *le_stock;
    QDoubleSpinBox *dbspbox_alert_price;
    QLabel *label_alert_bfh;
    QWidget *wid_step_range;
    QLabel *label_step_range;
    QDoubleSpinBox *dbspbox_step_range;
    QLabel *step_range_bfh;
    QWidget *wid_mid_line;
    QLabel *label_monitor;
    QTimeEdit *timeEdit_end;
    QTimeEdit *timeEdit_begin;
    QLabel *label_time_mid;
    QSpinBox *spinBox_quantity;
    QLabel *label_sell_num;
    QLabel *label_price_level;
    QLabel *label_total_num;
    QLabel *label_pt_max_num;
    QComboBox *combox_price_level;
    QPushButton *pbtn_all_quantity;
    QLabel *label_continue_sec;
    QSpinBox *spinBox_continue_time;
    QLabel *label_continue_time;
    QLabel *label_show_pic;
    QWidget *tab_eq_section_trd;
    QLabel *label_buytask_stock_2;
    QLineEdit *le_eqsec_stock;
    QDoubleSpinBox *dbspbox_eqsec_start_price;
    QLabel *label_eqsec_start_price;
    QDoubleSpinBox *dbspbox_eqsec_raise_percent;
    QLabel *label_raise_percent;
    QLabel *label_raise_percent_bfh;
    QLabel *label_raise_percent_sell;
    QLabel *label_raise_percent_bfh_2;
    QLabel *label_fall_percent;
    QLabel *label_raise_percent_buy;
    QDoubleSpinBox *dbspbox_eqsec_fall_percent;
    QLabel *label_price_level_3;
    QTimeEdit *timeEdit_eqsec_begin;
    QLabel *label_buytask_monitor_time_2;
    QTimeEdit *timeEdit_eqsec_end;
    QComboBox *combox_eqsec_price_level;
    QLabel *label_23;
    QLabel *lab_eqsec_quantity;
    QSpinBox *spinBox_eqsec_quantity;
    QPushButton *pbtn_add_eqsection_task;
    QDoubleSpinBox *dbspbox_eqsec_max_price;
    QLabel *label_eqsec_maxprice;
    QLabel *label_eqsec_maxprice_2;
    QDoubleSpinBox *dbspbox_eqsec_min_price;
    QCheckBox *cb_min_clear_trigger;
    QCheckBox *cb_max_stop_trigger;
    QSpinBox *spinBox_max_qty;
    QLabel *lab_max_quantity;
    QCheckBox *cb_max_qty;
    QLabel *lab_min_quantity;
    QSpinBox *spinBox_min_qty;
    QCheckBox *cb_min_qty;
    QWidget *wid_eqsec_rebounce_grp;
    QCheckBox *cb_eqsec_back_trigger;
    QDoubleSpinBox *spinBox_eqsec_rebounce;
    QLabel *label_eqsec_percent;
    QLabel *label_eqsec_rebounce;
    QCheckBox *cb_eqsec_rebounce;
    QWidget *tab_advsec_task;
    QLabel *label_bktest_adv_reb;
    QDoubleSpinBox *dbspb_adveq_max_price;
    QDoubleSpinBox *dbspb_adveq_start_capital;
    QLabel *label_raise_percent_rebounce_2;
    QSpinBox *spinBox_adveq_qty;
    QLabel *lab_bktest_adv_secnums;
    QDoubleSpinBox *dbspb_adveq_min_price;
    QLabel *lab_bktest_advsec_qty;
    QSpinBox *spb_adveq_section_count;
    QDoubleSpinBox *spb_adveq_rebounce;
    QLabel *label_bktest_maxprice_adv;
    QLabel *label_bktest_maxprice_5;
    QLabel *lab_bktest_start_capital_2;
    QLabel *label_buytask_stock_bktest;
    QLineEdit *le_adveq_stock;
    QPushButton *pbtn_add_adveq_task;
    QLabel *label_24;
    QTimeEdit *timeEdit_adveq_begin;
    QTimeEdit *timeEdit_adveq_end;
    QLabel *label_buytask_monitor_time_3;
    QComboBox *combox_adveq_price_level;
    QLabel *label_price_level_5;
    QPushButton *pbtn_adveq_need_capital;
    QWidget *tab_capital;
    QPlainTextEdit *pte_capital;
    QPushButton *pbtn_query_capital;
    QWidget *tab_log;
    QPlainTextEdit *pte_log;
    QWidget *tab_stkindex_task;
    QComboBox *combox_stkindex;
    QLabel *label_index_kind;
    QGroupBox *grp_relstock_trade;
    QLabel *label_sell_num_2;
    QSpinBox *spinBox_indtrd_quantity;
    QLabel *label_stock_3;
    QComboBox *indtrd_trd_price_level;
    QLineEdit *le_indtrd_stock;
    QLabel *label_price_level_4;
    QGroupBox *grp_choice_bs;
    QRadioButton *radioBtn_sell;
    QRadioButton *radioBtn_buy;
    QGroupBox *grp_updownkind;
    QRadioButton *radiobtn_cross_down;
    QRadioButton *radiobtn_cross_up;
    QLabel *label_index_pos;
    QDoubleSpinBox *dbspbox_index_val;
    QGroupBox *groupBox_kind_choice;
    QRadioButton *radiobtn_clearall;
    QRadioButton *radiobtn_reltrade;
    QRadioButton *radiobtn_alert;
    QPushButton *pbtn_add_indtrd_task;
    QLabel *label_index_continue_sec;
    QLabel *label_index_continue_time;
    QSpinBox *spinBox_index_continue_time;
    QTimeEdit *indtrd_timeEdit_end;
    QLabel *label_time_mid_2;
    QLabel *label_monitor_2;
    QTimeEdit *indtrd_timeEdit_begin;
    QMenuBar *menuBar;
    QMenu *menu_system;
    QMenu *menu_help;
    QMenu *menu_operate;
    QMenu *tool_menu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *TradeWinnerClass)
    {
        if (TradeWinnerClass->objectName().isEmpty())
            TradeWinnerClass->setObjectName(QStringLiteral("TradeWinnerClass"));
        TradeWinnerClass->resize(910, 620);
        actionClose = new QAction(TradeWinnerClass);
        actionClose->setObjectName(QStringLiteral("actionClose"));
        actionRestart = new QAction(TradeWinnerClass);
        actionRestart->setObjectName(QStringLiteral("actionRestart"));
        actionStopAllTask = new QAction(TradeWinnerClass);
        actionStopAllTask->setObjectName(QStringLiteral("actionStopAllTask"));
        actionOpenCalcWin = new QAction(TradeWinnerClass);
        actionOpenCalcWin->setObjectName(QStringLiteral("actionOpenCalcWin"));
        centralWidget = new QWidget(TradeWinnerClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        tabwid_holder = new QTabWidget(centralWidget);
        tabwid_holder->setObjectName(QStringLiteral("tabwid_holder"));
        tabwid_holder->setGeometry(QRect(0, 0, 911, 561));
        QFont font;
        font.setPointSize(12);
        tabwid_holder->setFont(font);
        tabwid_holder->setIconSize(QSize(32, 32));
        tab_task_list = new QWidget();
        tab_task_list->setObjectName(QStringLiteral("tab_task_list"));
        tbview_tasks = new QTableView(tab_task_list);
        tbview_tasks->setObjectName(QStringLiteral("tbview_tasks"));
        tbview_tasks->setGeometry(QRect(10, 30, 821, 461));
        tbview_tasks->setContextMenuPolicy(Qt::CustomContextMenu);
        tabwid_holder->addTab(tab_task_list, QString());
        tab_buytask = new QWidget();
        tab_buytask->setObjectName(QStringLiteral("tab_buytask"));
        label_buytask_alert_price = new QLabel(tab_buytask);
        label_buytask_alert_price->setObjectName(QStringLiteral("label_buytask_alert_price"));
        label_buytask_alert_price->setGeometry(QRect(70, 110, 71, 21));
        QFont font1;
        font1.setPointSize(10);
        label_buytask_alert_price->setFont(font1);
        label_buytask_alert_price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_buytask_stock = new QLabel(tab_buytask);
        label_buytask_stock->setObjectName(QStringLiteral("label_buytask_stock"));
        label_buytask_stock->setGeometry(QRect(70, 70, 71, 21));
        label_buytask_stock->setFont(font1);
        label_buytask_stock->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspbox_buytask_alert_percent = new QDoubleSpinBox(tab_buytask);
        dbspbox_buytask_alert_percent->setObjectName(QStringLiteral("dbspbox_buytask_alert_percent"));
        dbspbox_buytask_alert_percent->setGeometry(QRect(360, 110, 81, 31));
        dbspbox_buytask_alert_percent->setDecimals(1);
        dbspbox_buytask_alert_percent->setMaximum(1000);
        combox_buy_type = new QComboBox(tab_buytask);
        combox_buy_type->setObjectName(QStringLiteral("combox_buy_type"));
        combox_buy_type->setGeometry(QRect(80, 20, 441, 31));
        dbspbox_buytask_alert_price = new QDoubleSpinBox(tab_buytask);
        dbspbox_buytask_alert_price->setObjectName(QStringLiteral("dbspbox_buytask_alert_price"));
        dbspbox_buytask_alert_price->setGeometry(QRect(150, 110, 161, 31));
        dbspbox_buytask_alert_price->setDecimals(2);
        dbspbox_buytask_alert_price->setMaximum(999.99);
        le_buytask_stock = new QLineEdit(tab_buytask);
        le_buytask_stock->setObjectName(QStringLiteral("le_buytask_stock"));
        le_buytask_stock->setGeometry(QRect(150, 70, 161, 31));
        label_buytask_show_pic = new QLabel(tab_buytask);
        label_buytask_show_pic->setObjectName(QStringLiteral("label_buytask_show_pic"));
        label_buytask_show_pic->setGeometry(QRect(680, 0, 221, 241));
        pbtn_add_buytask = new QPushButton(tab_buytask);
        pbtn_add_buytask->setObjectName(QStringLiteral("pbtn_add_buytask"));
        pbtn_add_buytask->setGeometry(QRect(440, 420, 141, 23));
        wid_bt_retreat = new QWidget(tab_buytask);
        wid_bt_retreat->setObjectName(QStringLiteral("wid_bt_retreat"));
        wid_bt_retreat->setGeometry(QRect(50, 370, 401, 41));
        cb_bt_back_alert_trigger = new QCheckBox(wid_bt_retreat);
        cb_bt_back_alert_trigger->setObjectName(QStringLiteral("cb_bt_back_alert_trigger"));
        cb_bt_back_alert_trigger->setGeometry(QRect(250, 10, 111, 21));
        spinBox_bt_retreat = new QDoubleSpinBox(wid_bt_retreat);
        spinBox_bt_retreat->setObjectName(QStringLiteral("spinBox_bt_retreat"));
        spinBox_bt_retreat->setGeometry(QRect(100, 10, 101, 31));
        spinBox_bt_retreat->setDecimals(1);
        spinBox_bt_retreat->setMaximum(100);
        label_retreat_bfh_2 = new QLabel(wid_bt_retreat);
        label_retreat_bfh_2->setObjectName(QStringLiteral("label_retreat_bfh_2"));
        label_retreat_bfh_2->setGeometry(QRect(210, 13, 31, 20));
        label_bt_retreat = new QLabel(wid_bt_retreat);
        label_bt_retreat->setObjectName(QStringLiteral("label_bt_retreat"));
        label_bt_retreat->setGeometry(QRect(20, 10, 71, 21));
        label_bt_retreat->setFont(font1);
        label_bt_retreat->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        wid_bt_step_range = new QWidget(tab_buytask);
        wid_bt_step_range->setObjectName(QStringLiteral("wid_bt_step_range"));
        wid_bt_step_range->setGeometry(QRect(50, 430, 391, 81));
        label_bt_step_range = new QLabel(wid_bt_step_range);
        label_bt_step_range->setObjectName(QStringLiteral("label_bt_step_range"));
        label_bt_step_range->setGeometry(QRect(20, 0, 71, 21));
        label_bt_step_range->setFont(font1);
        label_bt_step_range->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspbox_bt_step_range = new QDoubleSpinBox(wid_bt_step_range);
        dbspbox_bt_step_range->setObjectName(QStringLiteral("dbspbox_bt_step_range"));
        dbspbox_bt_step_range->setGeometry(QRect(100, 0, 161, 31));
        dbspbox_bt_step_range->setDecimals(2);
        dbspbox_bt_step_range->setMaximum(999.99);
        step_range_bfh_2 = new QLabel(wid_bt_step_range);
        step_range_bfh_2->setObjectName(QStringLiteral("step_range_bfh_2"));
        step_range_bfh_2->setGeometry(QRect(270, 0, 31, 20));
        label_bt_times = new QLabel(wid_bt_step_range);
        label_bt_times->setObjectName(QStringLiteral("label_bt_times"));
        label_bt_times->setGeometry(QRect(20, 50, 71, 21));
        label_bt_times->setFont(font1);
        label_bt_times->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBox_buytask_times = new QSpinBox(wid_bt_step_range);
        spinBox_buytask_times->setObjectName(QStringLiteral("spinBox_buytask_times"));
        spinBox_buytask_times->setGeometry(QRect(100, 40, 101, 31));
        wid_bt_mid_line = new QWidget(tab_buytask);
        wid_bt_mid_line->setObjectName(QStringLiteral("wid_bt_mid_line"));
        wid_bt_mid_line->setGeometry(QRect(50, 150, 391, 221));
        lab_buytask_quantity = new QLabel(wid_bt_mid_line);
        lab_buytask_quantity->setObjectName(QStringLiteral("lab_buytask_quantity"));
        lab_buytask_quantity->setGeometry(QRect(0, 50, 91, 21));
        lab_buytask_quantity->setFont(font1);
        lab_buytask_quantity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_buytask_total_num = new QLabel(wid_bt_mid_line);
        label_buytask_total_num->setObjectName(QStringLiteral("label_buytask_total_num"));
        label_buytask_total_num->setGeometry(QRect(100, 100, 91, 21));
        label_buytask_total_num->setFont(font1);
        label_buytask_total_num->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        combox_bt_price_level = new QComboBox(wid_bt_mid_line);
        combox_bt_price_level->setObjectName(QStringLiteral("combox_bt_price_level"));
        combox_bt_price_level->setGeometry(QRect(100, 140, 291, 31));
        label_buytask_monitor_time = new QLabel(wid_bt_mid_line);
        label_buytask_monitor_time->setObjectName(QStringLiteral("label_buytask_monitor_time"));
        label_buytask_monitor_time->setGeometry(QRect(0, 180, 91, 21));
        label_buytask_monitor_time->setFont(font1);
        label_buytask_monitor_time->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_price_level_2 = new QLabel(wid_bt_mid_line);
        label_price_level_2->setObjectName(QStringLiteral("label_price_level_2"));
        label_price_level_2->setGeometry(QRect(0, 140, 91, 21));
        label_price_level_2->setFont(font1);
        label_price_level_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_21 = new QLabel(wid_bt_mid_line);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(230, 180, 21, 21));
        label_21->setFont(font1);
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        timeEdit_buytask_begin = new QTimeEdit(wid_bt_mid_line);
        timeEdit_buytask_begin->setObjectName(QStringLiteral("timeEdit_buytask_begin"));
        timeEdit_buytask_begin->setGeometry(QRect(100, 180, 118, 31));
        timeEdit_buytask_end = new QTimeEdit(wid_bt_mid_line);
        timeEdit_buytask_end->setObjectName(QStringLiteral("timeEdit_buytask_end"));
        timeEdit_buytask_end->setGeometry(QRect(273, 180, 118, 31));
        label_continue_time_2 = new QLabel(wid_bt_mid_line);
        label_continue_time_2->setObjectName(QStringLiteral("label_continue_time_2"));
        label_continue_time_2->setGeometry(QRect(20, 0, 71, 21));
        label_continue_time_2->setFont(font1);
        label_continue_time_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBox_buytask_continue_time = new QSpinBox(wid_bt_mid_line);
        spinBox_buytask_continue_time->setObjectName(QStringLiteral("spinBox_buytask_continue_time"));
        spinBox_buytask_continue_time->setGeometry(QRect(100, 0, 101, 31));
        label_22 = new QLabel(wid_bt_mid_line);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(230, 10, 46, 13));
        spinBox_buytask_quantity = new QSpinBox(wid_bt_mid_line);
        spinBox_buytask_quantity->setObjectName(QStringLiteral("spinBox_buytask_quantity"));
        spinBox_buytask_quantity->setGeometry(QRect(100, 51, 101, 31));
        label_19 = new QLabel(wid_bt_mid_line);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(0, 100, 91, 21));
        label_19->setFont(font1);
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pbtn_buytask_all_quantity = new QPushButton(wid_bt_mid_line);
        pbtn_buytask_all_quantity->setObjectName(QStringLiteral("pbtn_buytask_all_quantity"));
        pbtn_buytask_all_quantity->setGeometry(QRect(240, 100, 75, 23));
        cb_buytask_chase_limitup = new QCheckBox(wid_bt_mid_line);
        cb_buytask_chase_limitup->setObjectName(QStringLiteral("cb_buytask_chase_limitup"));
        cb_buytask_chase_limitup->setGeometry(QRect(230, 60, 111, 21));
        label_alert_bfh_2 = new QLabel(tab_buytask);
        label_alert_bfh_2->setObjectName(QStringLiteral("label_alert_bfh_2"));
        label_alert_bfh_2->setGeometry(QRect(450, 110, 31, 20));
        tabwid_holder->addTab(tab_buytask, QString());
        tab_sell_task = new QWidget();
        tab_sell_task->setObjectName(QStringLiteral("tab_sell_task"));
        wid_ticker = new QWidget(tab_sell_task);
        wid_ticker->setObjectName(QStringLiteral("wid_ticker"));
        wid_ticker->setGeometry(QRect(700, 270, 201, 251));
        lab_out_sell2 = new QLabel(wid_ticker);
        lab_out_sell2->setObjectName(QStringLiteral("lab_out_sell2"));
        lab_out_sell2->setGeometry(QRect(100, 90, 91, 16));
        lab_out_sell2->setFont(font1);
        label_4 = new QLabel(wid_ticker);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(50, 50, 46, 13));
        label_4->setFont(font1);
        label_5 = new QLabel(wid_ticker);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(50, 30, 46, 13));
        label_5->setFont(font1);
        label_6 = new QLabel(wid_ticker);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(50, 130, 211, 16));
        label_6->setFont(font1);
        lab_out_buy1 = new QLabel(wid_ticker);
        lab_out_buy1->setObjectName(QStringLiteral("lab_out_buy1"));
        lab_out_buy1->setGeometry(QRect(100, 150, 91, 16));
        lab_out_buy1->setFont(font1);
        label = new QLabel(wid_ticker);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(50, 110, 46, 13));
        label->setFont(font1);
        label_3 = new QLabel(wid_ticker);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(50, 70, 46, 13));
        label_3->setFont(font1);
        label_2 = new QLabel(wid_ticker);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(50, 90, 46, 13));
        label_2->setFont(font1);
        lab_out_buy3 = new QLabel(wid_ticker);
        lab_out_buy3->setObjectName(QStringLiteral("lab_out_buy3"));
        lab_out_buy3->setGeometry(QRect(100, 190, 91, 16));
        lab_out_buy3->setFont(font1);
        lab_out_buy5 = new QLabel(wid_ticker);
        lab_out_buy5->setObjectName(QStringLiteral("lab_out_buy5"));
        lab_out_buy5->setGeometry(QRect(100, 230, 91, 16));
        lab_out_buy5->setFont(font1);
        lab_out_sell4 = new QLabel(wid_ticker);
        lab_out_sell4->setObjectName(QStringLiteral("lab_out_sell4"));
        lab_out_sell4->setGeometry(QRect(100, 50, 71, 16));
        lab_out_sell4->setFont(font1);
        label_7 = new QLabel(wid_ticker);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(50, 230, 46, 13));
        label_7->setFont(font1);
        label_11 = new QLabel(wid_ticker);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(50, 170, 46, 13));
        label_11->setFont(font1);
        lab_out_sell1 = new QLabel(wid_ticker);
        lab_out_sell1->setObjectName(QStringLiteral("lab_out_sell1"));
        lab_out_sell1->setGeometry(QRect(100, 110, 91, 16));
        lab_out_sell1->setFont(font1);
        lab_out_sell3 = new QLabel(wid_ticker);
        lab_out_sell3->setObjectName(QStringLiteral("lab_out_sell3"));
        lab_out_sell3->setGeometry(QRect(100, 70, 81, 16));
        lab_out_sell3->setFont(font1);
        lab_out_buy4 = new QLabel(wid_ticker);
        lab_out_buy4->setObjectName(QStringLiteral("lab_out_buy4"));
        lab_out_buy4->setGeometry(QRect(100, 210, 91, 16));
        lab_out_buy4->setFont(font1);
        lab_out_sell5 = new QLabel(wid_ticker);
        lab_out_sell5->setObjectName(QStringLiteral("lab_out_sell5"));
        lab_out_sell5->setGeometry(QRect(100, 30, 81, 16));
        lab_out_sell5->setFont(font1);
        label_10 = new QLabel(wid_ticker);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(50, 210, 46, 13));
        label_10->setFont(font1);
        lab_out_buy2 = new QLabel(wid_ticker);
        lab_out_buy2->setObjectName(QStringLiteral("lab_out_buy2"));
        lab_out_buy2->setGeometry(QRect(100, 170, 101, 16));
        lab_out_buy2->setFont(font1);
        label_8 = new QLabel(wid_ticker);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(50, 150, 46, 13));
        label_8->setFont(font1);
        label_9 = new QLabel(wid_ticker);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(50, 190, 46, 13));
        label_9->setFont(font1);
        wid_retreat = new QWidget(tab_sell_task);
        wid_retreat->setObjectName(QStringLiteral("wid_retreat"));
        wid_retreat->setGeometry(QRect(50, 370, 401, 41));
        cb_back_alert_trigger = new QCheckBox(wid_retreat);
        cb_back_alert_trigger->setObjectName(QStringLiteral("cb_back_alert_trigger"));
        cb_back_alert_trigger->setGeometry(QRect(250, 10, 111, 21));
        spinBox_retreat = new QDoubleSpinBox(wid_retreat);
        spinBox_retreat->setObjectName(QStringLiteral("spinBox_retreat"));
        spinBox_retreat->setGeometry(QRect(100, 10, 101, 31));
        spinBox_retreat->setDecimals(1);
        spinBox_retreat->setMaximum(100);
        label_retreat_bfh = new QLabel(wid_retreat);
        label_retreat_bfh->setObjectName(QStringLiteral("label_retreat_bfh"));
        label_retreat_bfh->setGeometry(QRect(210, 13, 31, 20));
        label_retreat = new QLabel(wid_retreat);
        label_retreat->setObjectName(QStringLiteral("label_retreat"));
        label_retreat->setGeometry(QRect(20, 10, 71, 21));
        label_retreat->setFont(font1);
        label_retreat->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        combox_sell_type = new QComboBox(tab_sell_task);
        combox_sell_type->setObjectName(QStringLiteral("combox_sell_type"));
        combox_sell_type->setGeometry(QRect(80, 20, 441, 31));
        pbtn_add_task = new QPushButton(tab_sell_task);
        pbtn_add_task->setObjectName(QStringLiteral("pbtn_add_task"));
        pbtn_add_task->setGeometry(QRect(440, 420, 141, 23));
        dbspbox_alert_percent = new QDoubleSpinBox(tab_sell_task);
        dbspbox_alert_percent->setObjectName(QStringLiteral("dbspbox_alert_percent"));
        dbspbox_alert_percent->setGeometry(QRect(360, 120, 81, 31));
        dbspbox_alert_percent->setDecimals(1);
        dbspbox_alert_percent->setMaximum(1000);
        label_stock = new QLabel(tab_sell_task);
        label_stock->setObjectName(QStringLiteral("label_stock"));
        label_stock->setGeometry(QRect(70, 80, 71, 21));
        label_stock->setFont(font1);
        label_stock->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_alert_price = new QLabel(tab_sell_task);
        label_alert_price->setObjectName(QStringLiteral("label_alert_price"));
        label_alert_price->setGeometry(QRect(70, 120, 71, 21));
        label_alert_price->setFont(font1);
        label_alert_price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        le_stock = new QLineEdit(tab_sell_task);
        le_stock->setObjectName(QStringLiteral("le_stock"));
        le_stock->setGeometry(QRect(150, 80, 161, 31));
        dbspbox_alert_price = new QDoubleSpinBox(tab_sell_task);
        dbspbox_alert_price->setObjectName(QStringLiteral("dbspbox_alert_price"));
        dbspbox_alert_price->setGeometry(QRect(150, 120, 161, 31));
        dbspbox_alert_price->setDecimals(2);
        dbspbox_alert_price->setMaximum(999.99);
        label_alert_bfh = new QLabel(tab_sell_task);
        label_alert_bfh->setObjectName(QStringLiteral("label_alert_bfh"));
        label_alert_bfh->setGeometry(QRect(460, 130, 31, 20));
        wid_step_range = new QWidget(tab_sell_task);
        wid_step_range->setObjectName(QStringLiteral("wid_step_range"));
        wid_step_range->setGeometry(QRect(50, 430, 391, 41));
        label_step_range = new QLabel(wid_step_range);
        label_step_range->setObjectName(QStringLiteral("label_step_range"));
        label_step_range->setGeometry(QRect(20, 10, 71, 21));
        label_step_range->setFont(font1);
        label_step_range->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspbox_step_range = new QDoubleSpinBox(wid_step_range);
        dbspbox_step_range->setObjectName(QStringLiteral("dbspbox_step_range"));
        dbspbox_step_range->setGeometry(QRect(100, 10, 161, 31));
        dbspbox_step_range->setDecimals(2);
        dbspbox_step_range->setMaximum(999.99);
        step_range_bfh = new QLabel(wid_step_range);
        step_range_bfh->setObjectName(QStringLiteral("step_range_bfh"));
        step_range_bfh->setGeometry(QRect(280, 10, 31, 20));
        wid_mid_line = new QWidget(tab_sell_task);
        wid_mid_line->setObjectName(QStringLiteral("wid_mid_line"));
        wid_mid_line->setGeometry(QRect(50, 159, 401, 211));
        label_monitor = new QLabel(wid_mid_line);
        label_monitor->setObjectName(QStringLiteral("label_monitor"));
        label_monitor->setGeometry(QRect(0, 180, 91, 21));
        label_monitor->setFont(font1);
        label_monitor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        timeEdit_end = new QTimeEdit(wid_mid_line);
        timeEdit_end->setObjectName(QStringLiteral("timeEdit_end"));
        timeEdit_end->setGeometry(QRect(272, 180, 118, 31));
        timeEdit_begin = new QTimeEdit(wid_mid_line);
        timeEdit_begin->setObjectName(QStringLiteral("timeEdit_begin"));
        timeEdit_begin->setGeometry(QRect(100, 180, 118, 31));
        label_time_mid = new QLabel(wid_mid_line);
        label_time_mid->setObjectName(QStringLiteral("label_time_mid"));
        label_time_mid->setGeometry(QRect(230, 180, 21, 21));
        label_time_mid->setFont(font1);
        label_time_mid->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBox_quantity = new QSpinBox(wid_mid_line);
        spinBox_quantity->setObjectName(QStringLiteral("spinBox_quantity"));
        spinBox_quantity->setGeometry(QRect(100, 50, 101, 31));
        label_sell_num = new QLabel(wid_mid_line);
        label_sell_num->setObjectName(QStringLiteral("label_sell_num"));
        label_sell_num->setGeometry(QRect(0, 49, 91, 21));
        label_sell_num->setFont(font1);
        label_sell_num->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_price_level = new QLabel(wid_mid_line);
        label_price_level->setObjectName(QStringLiteral("label_price_level"));
        label_price_level->setGeometry(QRect(0, 139, 91, 21));
        label_price_level->setFont(font1);
        label_price_level->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_total_num = new QLabel(wid_mid_line);
        label_total_num->setObjectName(QStringLiteral("label_total_num"));
        label_total_num->setGeometry(QRect(100, 99, 91, 21));
        label_total_num->setFont(font1);
        label_total_num->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_pt_max_num = new QLabel(wid_mid_line);
        label_pt_max_num->setObjectName(QStringLiteral("label_pt_max_num"));
        label_pt_max_num->setGeometry(QRect(0, 99, 91, 21));
        label_pt_max_num->setFont(font1);
        label_pt_max_num->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        combox_price_level = new QComboBox(wid_mid_line);
        combox_price_level->setObjectName(QStringLiteral("combox_price_level"));
        combox_price_level->setGeometry(QRect(100, 139, 291, 31));
        pbtn_all_quantity = new QPushButton(wid_mid_line);
        pbtn_all_quantity->setObjectName(QStringLiteral("pbtn_all_quantity"));
        pbtn_all_quantity->setGeometry(QRect(240, 99, 75, 23));
        label_continue_sec = new QLabel(wid_mid_line);
        label_continue_sec->setObjectName(QStringLiteral("label_continue_sec"));
        label_continue_sec->setGeometry(QRect(220, 20, 46, 13));
        spinBox_continue_time = new QSpinBox(wid_mid_line);
        spinBox_continue_time->setObjectName(QStringLiteral("spinBox_continue_time"));
        spinBox_continue_time->setGeometry(QRect(100, 10, 101, 31));
        label_continue_time = new QLabel(wid_mid_line);
        label_continue_time->setObjectName(QStringLiteral("label_continue_time"));
        label_continue_time->setGeometry(QRect(20, 10, 71, 21));
        label_continue_time->setFont(font1);
        label_continue_time->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_show_pic = new QLabel(tab_sell_task);
        label_show_pic->setObjectName(QStringLiteral("label_show_pic"));
        label_show_pic->setGeometry(QRect(680, 0, 221, 241));
        tabwid_holder->addTab(tab_sell_task, QString());
        tab_eq_section_trd = new QWidget();
        tab_eq_section_trd->setObjectName(QStringLiteral("tab_eq_section_trd"));
        label_buytask_stock_2 = new QLabel(tab_eq_section_trd);
        label_buytask_stock_2->setObjectName(QStringLiteral("label_buytask_stock_2"));
        label_buytask_stock_2->setGeometry(QRect(90, 30, 71, 21));
        label_buytask_stock_2->setFont(font1);
        label_buytask_stock_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        le_eqsec_stock = new QLineEdit(tab_eq_section_trd);
        le_eqsec_stock->setObjectName(QStringLiteral("le_eqsec_stock"));
        le_eqsec_stock->setGeometry(QRect(170, 30, 161, 31));
        dbspbox_eqsec_start_price = new QDoubleSpinBox(tab_eq_section_trd);
        dbspbox_eqsec_start_price->setObjectName(QStringLiteral("dbspbox_eqsec_start_price"));
        dbspbox_eqsec_start_price->setGeometry(QRect(170, 70, 161, 31));
        dbspbox_eqsec_start_price->setDecimals(2);
        dbspbox_eqsec_start_price->setMaximum(999.99);
        label_eqsec_start_price = new QLabel(tab_eq_section_trd);
        label_eqsec_start_price->setObjectName(QStringLiteral("label_eqsec_start_price"));
        label_eqsec_start_price->setGeometry(QRect(90, 70, 71, 21));
        label_eqsec_start_price->setFont(font1);
        label_eqsec_start_price->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspbox_eqsec_raise_percent = new QDoubleSpinBox(tab_eq_section_trd);
        dbspbox_eqsec_raise_percent->setObjectName(QStringLiteral("dbspbox_eqsec_raise_percent"));
        dbspbox_eqsec_raise_percent->setGeometry(QRect(170, 110, 81, 31));
        dbspbox_eqsec_raise_percent->setDecimals(1);
        dbspbox_eqsec_raise_percent->setMaximum(1000);
        label_raise_percent = new QLabel(tab_eq_section_trd);
        label_raise_percent->setObjectName(QStringLiteral("label_raise_percent"));
        label_raise_percent->setGeometry(QRect(90, 110, 71, 21));
        label_raise_percent->setFont(font1);
        label_raise_percent->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_raise_percent_bfh = new QLabel(tab_eq_section_trd);
        label_raise_percent_bfh->setObjectName(QStringLiteral("label_raise_percent_bfh"));
        label_raise_percent_bfh->setGeometry(QRect(250, 110, 31, 21));
        label_raise_percent_bfh->setFont(font);
        label_raise_percent_bfh->setAlignment(Qt::AlignCenter);
        label_raise_percent_sell = new QLabel(tab_eq_section_trd);
        label_raise_percent_sell->setObjectName(QStringLiteral("label_raise_percent_sell"));
        label_raise_percent_sell->setGeometry(QRect(280, 110, 51, 21));
        label_raise_percent_sell->setFont(font1);
        label_raise_percent_sell->setAlignment(Qt::AlignCenter);
        label_raise_percent_bfh_2 = new QLabel(tab_eq_section_trd);
        label_raise_percent_bfh_2->setObjectName(QStringLiteral("label_raise_percent_bfh_2"));
        label_raise_percent_bfh_2->setGeometry(QRect(250, 150, 31, 21));
        label_raise_percent_bfh_2->setFont(font);
        label_raise_percent_bfh_2->setAlignment(Qt::AlignCenter);
        label_fall_percent = new QLabel(tab_eq_section_trd);
        label_fall_percent->setObjectName(QStringLiteral("label_fall_percent"));
        label_fall_percent->setGeometry(QRect(90, 150, 71, 21));
        label_fall_percent->setFont(font1);
        label_fall_percent->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_raise_percent_buy = new QLabel(tab_eq_section_trd);
        label_raise_percent_buy->setObjectName(QStringLiteral("label_raise_percent_buy"));
        label_raise_percent_buy->setGeometry(QRect(280, 150, 51, 21));
        label_raise_percent_buy->setFont(font1);
        label_raise_percent_buy->setAlignment(Qt::AlignCenter);
        dbspbox_eqsec_fall_percent = new QDoubleSpinBox(tab_eq_section_trd);
        dbspbox_eqsec_fall_percent->setObjectName(QStringLiteral("dbspbox_eqsec_fall_percent"));
        dbspbox_eqsec_fall_percent->setGeometry(QRect(170, 150, 81, 31));
        dbspbox_eqsec_fall_percent->setDecimals(1);
        dbspbox_eqsec_fall_percent->setMaximum(1000);
        label_price_level_3 = new QLabel(tab_eq_section_trd);
        label_price_level_3->setObjectName(QStringLiteral("label_price_level_3"));
        label_price_level_3->setGeometry(QRect(70, 430, 91, 21));
        label_price_level_3->setFont(font1);
        label_price_level_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        timeEdit_eqsec_begin = new QTimeEdit(tab_eq_section_trd);
        timeEdit_eqsec_begin->setObjectName(QStringLiteral("timeEdit_eqsec_begin"));
        timeEdit_eqsec_begin->setGeometry(QRect(170, 470, 118, 31));
        label_buytask_monitor_time_2 = new QLabel(tab_eq_section_trd);
        label_buytask_monitor_time_2->setObjectName(QStringLiteral("label_buytask_monitor_time_2"));
        label_buytask_monitor_time_2->setGeometry(QRect(70, 470, 91, 21));
        label_buytask_monitor_time_2->setFont(font1);
        label_buytask_monitor_time_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        timeEdit_eqsec_end = new QTimeEdit(tab_eq_section_trd);
        timeEdit_eqsec_end->setObjectName(QStringLiteral("timeEdit_eqsec_end"));
        timeEdit_eqsec_end->setGeometry(QRect(340, 470, 118, 31));
        combox_eqsec_price_level = new QComboBox(tab_eq_section_trd);
        combox_eqsec_price_level->setObjectName(QStringLiteral("combox_eqsec_price_level"));
        combox_eqsec_price_level->setGeometry(QRect(170, 430, 288, 31));
        label_23 = new QLabel(tab_eq_section_trd);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(300, 470, 21, 21));
        label_23->setFont(font1);
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lab_eqsec_quantity = new QLabel(tab_eq_section_trd);
        lab_eqsec_quantity->setObjectName(QStringLiteral("lab_eqsec_quantity"));
        lab_eqsec_quantity->setGeometry(QRect(70, 230, 91, 21));
        lab_eqsec_quantity->setFont(font1);
        lab_eqsec_quantity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBox_eqsec_quantity = new QSpinBox(tab_eq_section_trd);
        spinBox_eqsec_quantity->setObjectName(QStringLiteral("spinBox_eqsec_quantity"));
        spinBox_eqsec_quantity->setGeometry(QRect(170, 231, 101, 31));
        pbtn_add_eqsection_task = new QPushButton(tab_eq_section_trd);
        pbtn_add_eqsection_task->setObjectName(QStringLiteral("pbtn_add_eqsection_task"));
        pbtn_add_eqsection_task->setGeometry(QRect(470, 460, 141, 23));
        dbspbox_eqsec_max_price = new QDoubleSpinBox(tab_eq_section_trd);
        dbspbox_eqsec_max_price->setObjectName(QStringLiteral("dbspbox_eqsec_max_price"));
        dbspbox_eqsec_max_price->setGeometry(QRect(170, 350, 101, 31));
        dbspbox_eqsec_max_price->setDecimals(2);
        dbspbox_eqsec_max_price->setMaximum(999.99);
        label_eqsec_maxprice = new QLabel(tab_eq_section_trd);
        label_eqsec_maxprice->setObjectName(QStringLiteral("label_eqsec_maxprice"));
        label_eqsec_maxprice->setGeometry(QRect(70, 350, 91, 21));
        label_eqsec_maxprice->setFont(font1);
        label_eqsec_maxprice->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_eqsec_maxprice_2 = new QLabel(tab_eq_section_trd);
        label_eqsec_maxprice_2->setObjectName(QStringLiteral("label_eqsec_maxprice_2"));
        label_eqsec_maxprice_2->setGeometry(QRect(70, 390, 91, 21));
        label_eqsec_maxprice_2->setFont(font1);
        label_eqsec_maxprice_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspbox_eqsec_min_price = new QDoubleSpinBox(tab_eq_section_trd);
        dbspbox_eqsec_min_price->setObjectName(QStringLiteral("dbspbox_eqsec_min_price"));
        dbspbox_eqsec_min_price->setGeometry(QRect(170, 390, 101, 31));
        dbspbox_eqsec_min_price->setDecimals(2);
        dbspbox_eqsec_min_price->setMaximum(999.99);
        cb_min_clear_trigger = new QCheckBox(tab_eq_section_trd);
        cb_min_clear_trigger->setObjectName(QStringLiteral("cb_min_clear_trigger"));
        cb_min_clear_trigger->setGeometry(QRect(280, 400, 61, 21));
        cb_max_stop_trigger = new QCheckBox(tab_eq_section_trd);
        cb_max_stop_trigger->setObjectName(QStringLiteral("cb_max_stop_trigger"));
        cb_max_stop_trigger->setGeometry(QRect(280, 360, 61, 21));
        spinBox_max_qty = new QSpinBox(tab_eq_section_trd);
        spinBox_max_qty->setObjectName(QStringLiteral("spinBox_max_qty"));
        spinBox_max_qty->setGeometry(QRect(170, 271, 101, 31));
        spinBox_max_qty->setMaximum(999999999);
        lab_max_quantity = new QLabel(tab_eq_section_trd);
        lab_max_quantity->setObjectName(QStringLiteral("lab_max_quantity"));
        lab_max_quantity->setGeometry(QRect(70, 270, 91, 21));
        lab_max_quantity->setFont(font1);
        lab_max_quantity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cb_max_qty = new QCheckBox(tab_eq_section_trd);
        cb_max_qty->setObjectName(QStringLiteral("cb_max_qty"));
        cb_max_qty->setGeometry(QRect(280, 280, 61, 21));
        lab_min_quantity = new QLabel(tab_eq_section_trd);
        lab_min_quantity->setObjectName(QStringLiteral("lab_min_quantity"));
        lab_min_quantity->setGeometry(QRect(70, 310, 91, 21));
        lab_min_quantity->setFont(font1);
        lab_min_quantity->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBox_min_qty = new QSpinBox(tab_eq_section_trd);
        spinBox_min_qty->setObjectName(QStringLiteral("spinBox_min_qty"));
        spinBox_min_qty->setGeometry(QRect(170, 311, 101, 31));
        spinBox_min_qty->setMaximum(999999999);
        cb_min_qty = new QCheckBox(tab_eq_section_trd);
        cb_min_qty->setObjectName(QStringLiteral("cb_min_qty"));
        cb_min_qty->setGeometry(QRect(280, 320, 61, 21));
        wid_eqsec_rebounce_grp = new QWidget(tab_eq_section_trd);
        wid_eqsec_rebounce_grp->setObjectName(QStringLiteral("wid_eqsec_rebounce_grp"));
        wid_eqsec_rebounce_grp->setGeometry(QRect(70, 180, 311, 41));
        cb_eqsec_back_trigger = new QCheckBox(wid_eqsec_rebounce_grp);
        cb_eqsec_back_trigger->setObjectName(QStringLiteral("cb_eqsec_back_trigger"));
        cb_eqsec_back_trigger->setGeometry(QRect(220, 12, 91, 21));
        spinBox_eqsec_rebounce = new QDoubleSpinBox(wid_eqsec_rebounce_grp);
        spinBox_eqsec_rebounce->setObjectName(QStringLiteral("spinBox_eqsec_rebounce"));
        spinBox_eqsec_rebounce->setGeometry(QRect(100, 10, 101, 31));
        spinBox_eqsec_rebounce->setDecimals(1);
        spinBox_eqsec_rebounce->setMaximum(100);
        label_eqsec_percent = new QLabel(wid_eqsec_rebounce_grp);
        label_eqsec_percent->setObjectName(QStringLiteral("label_eqsec_percent"));
        label_eqsec_percent->setGeometry(QRect(200, 13, 16, 20));
        label_eqsec_rebounce = new QLabel(wid_eqsec_rebounce_grp);
        label_eqsec_rebounce->setObjectName(QStringLiteral("label_eqsec_rebounce"));
        label_eqsec_rebounce->setGeometry(QRect(20, 10, 71, 21));
        label_eqsec_rebounce->setFont(font1);
        label_eqsec_rebounce->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cb_eqsec_rebounce = new QCheckBox(tab_eq_section_trd);
        cb_eqsec_rebounce->setObjectName(QStringLiteral("cb_eqsec_rebounce"));
        cb_eqsec_rebounce->setGeometry(QRect(390, 192, 92, 21));
        tabwid_holder->addTab(tab_eq_section_trd, QString());
        tab_advsec_task = new QWidget();
        tab_advsec_task->setObjectName(QStringLiteral("tab_advsec_task"));
        label_bktest_adv_reb = new QLabel(tab_advsec_task);
        label_bktest_adv_reb->setObjectName(QStringLiteral("label_bktest_adv_reb"));
        label_bktest_adv_reb->setGeometry(QRect(100, 200, 61, 21));
        label_bktest_adv_reb->setFont(font1);
        label_bktest_adv_reb->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspb_adveq_max_price = new QDoubleSpinBox(tab_advsec_task);
        dbspb_adveq_max_price->setObjectName(QStringLiteral("dbspb_adveq_max_price"));
        dbspb_adveq_max_price->setGeometry(QRect(170, 80, 101, 31));
        dbspb_adveq_max_price->setDecimals(2);
        dbspb_adveq_max_price->setMaximum(999.99);
        dbspb_adveq_max_price->setSingleStep(0.1);
        dbspb_adveq_start_capital = new QDoubleSpinBox(tab_advsec_task);
        dbspb_adveq_start_capital->setObjectName(QStringLiteral("dbspb_adveq_start_capital"));
        dbspb_adveq_start_capital->setEnabled(false);
        dbspb_adveq_start_capital->setGeometry(QRect(170, 280, 111, 31));
        dbspb_adveq_start_capital->setDecimals(2);
        dbspb_adveq_start_capital->setMaximum(1e+08);
        dbspb_adveq_start_capital->setSingleStep(1000);
        dbspb_adveq_start_capital->setValue(1000);
        label_raise_percent_rebounce_2 = new QLabel(tab_advsec_task);
        label_raise_percent_rebounce_2->setObjectName(QStringLiteral("label_raise_percent_rebounce_2"));
        label_raise_percent_rebounce_2->setGeometry(QRect(270, 210, 31, 21));
        label_raise_percent_rebounce_2->setFont(font);
        label_raise_percent_rebounce_2->setAlignment(Qt::AlignCenter);
        spinBox_adveq_qty = new QSpinBox(tab_advsec_task);
        spinBox_adveq_qty->setObjectName(QStringLiteral("spinBox_adveq_qty"));
        spinBox_adveq_qty->setGeometry(QRect(170, 240, 101, 31));
        spinBox_adveq_qty->setMaximum(100000);
        spinBox_adveq_qty->setSingleStep(100);
        spinBox_adveq_qty->setValue(100);
        lab_bktest_adv_secnums = new QLabel(tab_advsec_task);
        lab_bktest_adv_secnums->setObjectName(QStringLiteral("lab_bktest_adv_secnums"));
        lab_bktest_adv_secnums->setGeometry(QRect(80, 160, 81, 21));
        lab_bktest_adv_secnums->setFont(font1);
        lab_bktest_adv_secnums->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspb_adveq_min_price = new QDoubleSpinBox(tab_advsec_task);
        dbspb_adveq_min_price->setObjectName(QStringLiteral("dbspb_adveq_min_price"));
        dbspb_adveq_min_price->setGeometry(QRect(170, 120, 101, 31));
        dbspb_adveq_min_price->setDecimals(2);
        dbspb_adveq_min_price->setMaximum(999.99);
        dbspb_adveq_min_price->setSingleStep(0.1);
        lab_bktest_advsec_qty = new QLabel(tab_advsec_task);
        lab_bktest_advsec_qty->setObjectName(QStringLiteral("lab_bktest_advsec_qty"));
        lab_bktest_advsec_qty->setGeometry(QRect(80, 240, 81, 21));
        lab_bktest_advsec_qty->setFont(font1);
        lab_bktest_advsec_qty->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spb_adveq_section_count = new QSpinBox(tab_advsec_task);
        spb_adveq_section_count->setObjectName(QStringLiteral("spb_adveq_section_count"));
        spb_adveq_section_count->setGeometry(QRect(170, 160, 101, 31));
        spb_adveq_section_count->setMaximum(100000);
        spb_adveq_section_count->setSingleStep(1);
        spb_adveq_section_count->setValue(2);
        spb_adveq_rebounce = new QDoubleSpinBox(tab_advsec_task);
        spb_adveq_rebounce->setObjectName(QStringLiteral("spb_adveq_rebounce"));
        spb_adveq_rebounce->setGeometry(QRect(170, 200, 101, 31));
        spb_adveq_rebounce->setDecimals(1);
        spb_adveq_rebounce->setMaximum(100);
        spb_adveq_rebounce->setSingleStep(0.1);
        spb_adveq_rebounce->setValue(0.1);
        label_bktest_maxprice_adv = new QLabel(tab_advsec_task);
        label_bktest_maxprice_adv->setObjectName(QStringLiteral("label_bktest_maxprice_adv"));
        label_bktest_maxprice_adv->setGeometry(QRect(100, 80, 61, 21));
        label_bktest_maxprice_adv->setFont(font1);
        label_bktest_maxprice_adv->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_bktest_maxprice_5 = new QLabel(tab_advsec_task);
        label_bktest_maxprice_5->setObjectName(QStringLiteral("label_bktest_maxprice_5"));
        label_bktest_maxprice_5->setGeometry(QRect(100, 120, 61, 21));
        label_bktest_maxprice_5->setFont(font1);
        label_bktest_maxprice_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lab_bktest_start_capital_2 = new QLabel(tab_advsec_task);
        lab_bktest_start_capital_2->setObjectName(QStringLiteral("lab_bktest_start_capital_2"));
        lab_bktest_start_capital_2->setGeometry(QRect(100, 280, 61, 21));
        lab_bktest_start_capital_2->setFont(font1);
        lab_bktest_start_capital_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_buytask_stock_bktest = new QLabel(tab_advsec_task);
        label_buytask_stock_bktest->setObjectName(QStringLiteral("label_buytask_stock_bktest"));
        label_buytask_stock_bktest->setGeometry(QRect(85, 40, 71, 21));
        label_buytask_stock_bktest->setFont(font1);
        label_buytask_stock_bktest->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        le_adveq_stock = new QLineEdit(tab_advsec_task);
        le_adveq_stock->setObjectName(QStringLiteral("le_adveq_stock"));
        le_adveq_stock->setGeometry(QRect(170, 40, 161, 31));
        pbtn_add_adveq_task = new QPushButton(tab_advsec_task);
        pbtn_add_adveq_task->setObjectName(QStringLiteral("pbtn_add_adveq_task"));
        pbtn_add_adveq_task->setGeometry(QRect(470, 340, 141, 23));
        label_24 = new QLabel(tab_advsec_task);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(300, 360, 21, 21));
        label_24->setFont(font1);
        label_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        timeEdit_adveq_begin = new QTimeEdit(tab_advsec_task);
        timeEdit_adveq_begin->setObjectName(QStringLiteral("timeEdit_adveq_begin"));
        timeEdit_adveq_begin->setGeometry(QRect(170, 360, 118, 31));
        timeEdit_adveq_end = new QTimeEdit(tab_advsec_task);
        timeEdit_adveq_end->setObjectName(QStringLiteral("timeEdit_adveq_end"));
        timeEdit_adveq_end->setGeometry(QRect(340, 360, 118, 31));
        label_buytask_monitor_time_3 = new QLabel(tab_advsec_task);
        label_buytask_monitor_time_3->setObjectName(QStringLiteral("label_buytask_monitor_time_3"));
        label_buytask_monitor_time_3->setGeometry(QRect(70, 360, 91, 21));
        label_buytask_monitor_time_3->setFont(font1);
        label_buytask_monitor_time_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        combox_adveq_price_level = new QComboBox(tab_advsec_task);
        combox_adveq_price_level->setObjectName(QStringLiteral("combox_adveq_price_level"));
        combox_adveq_price_level->setGeometry(QRect(170, 320, 288, 31));
        label_price_level_5 = new QLabel(tab_advsec_task);
        label_price_level_5->setObjectName(QStringLiteral("label_price_level_5"));
        label_price_level_5->setGeometry(QRect(70, 320, 91, 21));
        label_price_level_5->setFont(font1);
        label_price_level_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        pbtn_adveq_need_capital = new QPushButton(tab_advsec_task);
        pbtn_adveq_need_capital->setObjectName(QStringLiteral("pbtn_adveq_need_capital"));
        pbtn_adveq_need_capital->setGeometry(QRect(290, 280, 111, 23));
        QFont font2;
        font2.setPointSize(11);
        pbtn_adveq_need_capital->setFont(font2);
        tabwid_holder->addTab(tab_advsec_task, QString());
        tab_capital = new QWidget();
        tab_capital->setObjectName(QStringLiteral("tab_capital"));
        pte_capital = new QPlainTextEdit(tab_capital);
        pte_capital->setObjectName(QStringLiteral("pte_capital"));
        pte_capital->setGeometry(QRect(20, 20, 681, 481));
        pte_capital->setStyleSheet(QLatin1String("\n"
"background-color: rgb(255, 255,255);"));
        pte_capital->setFrameShape(QFrame::Panel);
        pte_capital->setFrameShadow(QFrame::Plain);
        pbtn_query_capital = new QPushButton(tab_capital);
        pbtn_query_capital->setObjectName(QStringLiteral("pbtn_query_capital"));
        pbtn_query_capital->setGeometry(QRect(750, 220, 81, 31));
        tabwid_holder->addTab(tab_capital, QString());
        tab_log = new QWidget();
        tab_log->setObjectName(QStringLiteral("tab_log"));
        pte_log = new QPlainTextEdit(tab_log);
        pte_log->setObjectName(QStringLiteral("pte_log"));
        pte_log->setGeometry(QRect(0, 0, 911, 541));
        tabwid_holder->addTab(tab_log, QString());
        tab_stkindex_task = new QWidget();
        tab_stkindex_task->setObjectName(QStringLiteral("tab_stkindex_task"));
        combox_stkindex = new QComboBox(tab_stkindex_task);
        combox_stkindex->setObjectName(QStringLiteral("combox_stkindex"));
        combox_stkindex->setGeometry(QRect(170, 40, 201, 31));
        label_index_kind = new QLabel(tab_stkindex_task);
        label_index_kind->setObjectName(QStringLiteral("label_index_kind"));
        label_index_kind->setGeometry(QRect(90, 50, 71, 21));
        label_index_kind->setFont(font1);
        label_index_kind->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        grp_relstock_trade = new QGroupBox(tab_stkindex_task);
        grp_relstock_trade->setObjectName(QStringLiteral("grp_relstock_trade"));
        grp_relstock_trade->setGeometry(QRect(100, 210, 421, 171));
        label_sell_num_2 = new QLabel(grp_relstock_trade);
        label_sell_num_2->setObjectName(QStringLiteral("label_sell_num_2"));
        label_sell_num_2->setGeometry(QRect(8, 69, 91, 21));
        label_sell_num_2->setFont(font1);
        label_sell_num_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBox_indtrd_quantity = new QSpinBox(grp_relstock_trade);
        spinBox_indtrd_quantity->setObjectName(QStringLiteral("spinBox_indtrd_quantity"));
        spinBox_indtrd_quantity->setGeometry(QRect(108, 70, 101, 31));
        label_stock_3 = new QLabel(grp_relstock_trade);
        label_stock_3->setObjectName(QStringLiteral("label_stock_3"));
        label_stock_3->setGeometry(QRect(28, 19, 71, 21));
        label_stock_3->setFont(font1);
        label_stock_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        indtrd_trd_price_level = new QComboBox(grp_relstock_trade);
        indtrd_trd_price_level->setObjectName(QStringLiteral("indtrd_trd_price_level"));
        indtrd_trd_price_level->setGeometry(QRect(108, 119, 291, 31));
        le_indtrd_stock = new QLineEdit(grp_relstock_trade);
        le_indtrd_stock->setObjectName(QStringLiteral("le_indtrd_stock"));
        le_indtrd_stock->setGeometry(QRect(108, 19, 161, 31));
        label_price_level_4 = new QLabel(grp_relstock_trade);
        label_price_level_4->setObjectName(QStringLiteral("label_price_level_4"));
        label_price_level_4->setGeometry(QRect(8, 119, 91, 21));
        label_price_level_4->setFont(font1);
        label_price_level_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        grp_choice_bs = new QGroupBox(grp_relstock_trade);
        grp_choice_bs->setObjectName(QStringLiteral("grp_choice_bs"));
        grp_choice_bs->setGeometry(QRect(240, 70, 141, 41));
        radioBtn_sell = new QRadioButton(grp_choice_bs);
        radioBtn_sell->setObjectName(QStringLiteral("radioBtn_sell"));
        radioBtn_sell->setGeometry(QRect(10, 10, 61, 18));
        radioBtn_buy = new QRadioButton(grp_choice_bs);
        radioBtn_buy->setObjectName(QStringLiteral("radioBtn_buy"));
        radioBtn_buy->setGeometry(QRect(80, 10, 51, 18));
        grp_updownkind = new QGroupBox(tab_stkindex_task);
        grp_updownkind->setObjectName(QStringLiteral("grp_updownkind"));
        grp_updownkind->setGeometry(QRect(370, 80, 141, 41));
        radiobtn_cross_down = new QRadioButton(grp_updownkind);
        radiobtn_cross_down->setObjectName(QStringLiteral("radiobtn_cross_down"));
        radiobtn_cross_down->setGeometry(QRect(10, 10, 82, 18));
        radiobtn_cross_down->setChecked(true);
        radiobtn_cross_up = new QRadioButton(grp_updownkind);
        radiobtn_cross_up->setObjectName(QStringLiteral("radiobtn_cross_up"));
        radiobtn_cross_up->setGeometry(QRect(80, 10, 61, 18));
        label_index_pos = new QLabel(tab_stkindex_task);
        label_index_pos->setObjectName(QStringLiteral("label_index_pos"));
        label_index_pos->setGeometry(QRect(90, 80, 71, 21));
        label_index_pos->setFont(font1);
        label_index_pos->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        dbspbox_index_val = new QDoubleSpinBox(tab_stkindex_task);
        dbspbox_index_val->setObjectName(QStringLiteral("dbspbox_index_val"));
        dbspbox_index_val->setGeometry(QRect(170, 80, 161, 31));
        dbspbox_index_val->setDecimals(2);
        dbspbox_index_val->setMaximum(9999.99);
        groupBox_kind_choice = new QGroupBox(tab_stkindex_task);
        groupBox_kind_choice->setObjectName(QStringLiteral("groupBox_kind_choice"));
        groupBox_kind_choice->setGeometry(QRect(100, 160, 241, 41));
        radiobtn_clearall = new QRadioButton(groupBox_kind_choice);
        radiobtn_clearall->setObjectName(QStringLiteral("radiobtn_clearall"));
        radiobtn_clearall->setGeometry(QRect(170, 10, 71, 20));
        radiobtn_reltrade = new QRadioButton(groupBox_kind_choice);
        radiobtn_reltrade->setObjectName(QStringLiteral("radiobtn_reltrade"));
        radiobtn_reltrade->setGeometry(QRect(80, 10, 88, 20));
        radiobtn_reltrade->setChecked(true);
        radiobtn_alert = new QRadioButton(groupBox_kind_choice);
        radiobtn_alert->setObjectName(QStringLiteral("radiobtn_alert"));
        radiobtn_alert->setGeometry(QRect(10, 10, 61, 20));
        pbtn_add_indtrd_task = new QPushButton(tab_stkindex_task);
        pbtn_add_indtrd_task->setObjectName(QStringLiteral("pbtn_add_indtrd_task"));
        pbtn_add_indtrd_task->setGeometry(QRect(520, 440, 141, 23));
        label_index_continue_sec = new QLabel(tab_stkindex_task);
        label_index_continue_sec->setObjectName(QStringLiteral("label_index_continue_sec"));
        label_index_continue_sec->setGeometry(QRect(290, 130, 46, 13));
        label_index_continue_time = new QLabel(tab_stkindex_task);
        label_index_continue_time->setObjectName(QStringLiteral("label_index_continue_time"));
        label_index_continue_time->setGeometry(QRect(90, 120, 71, 21));
        label_index_continue_time->setFont(font1);
        label_index_continue_time->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        spinBox_index_continue_time = new QSpinBox(tab_stkindex_task);
        spinBox_index_continue_time->setObjectName(QStringLiteral("spinBox_index_continue_time"));
        spinBox_index_continue_time->setGeometry(QRect(170, 120, 101, 31));
        spinBox_index_continue_time->setMaximum(120);
        indtrd_timeEdit_end = new QTimeEdit(tab_stkindex_task);
        indtrd_timeEdit_end->setObjectName(QStringLiteral("indtrd_timeEdit_end"));
        indtrd_timeEdit_end->setGeometry(QRect(340, 390, 118, 31));
        label_time_mid_2 = new QLabel(tab_stkindex_task);
        label_time_mid_2->setObjectName(QStringLiteral("label_time_mid_2"));
        label_time_mid_2->setGeometry(QRect(298, 390, 21, 21));
        label_time_mid_2->setFont(font1);
        label_time_mid_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_monitor_2 = new QLabel(tab_stkindex_task);
        label_monitor_2->setObjectName(QStringLiteral("label_monitor_2"));
        label_monitor_2->setGeometry(QRect(68, 390, 91, 21));
        label_monitor_2->setFont(font1);
        label_monitor_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        indtrd_timeEdit_begin = new QTimeEdit(tab_stkindex_task);
        indtrd_timeEdit_begin->setObjectName(QStringLiteral("indtrd_timeEdit_begin"));
        indtrd_timeEdit_begin->setGeometry(QRect(168, 390, 118, 31));
        tabwid_holder->addTab(tab_stkindex_task, QString());
        TradeWinnerClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(TradeWinnerClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 910, 23));
        menu_system = new QMenu(menuBar);
        menu_system->setObjectName(QStringLiteral("menu_system"));
        menu_help = new QMenu(menuBar);
        menu_help->setObjectName(QStringLiteral("menu_help"));
        menu_operate = new QMenu(menuBar);
        menu_operate->setObjectName(QStringLiteral("menu_operate"));
        tool_menu = new QMenu(menuBar);
        tool_menu->setObjectName(QStringLiteral("tool_menu"));
        TradeWinnerClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(TradeWinnerClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        TradeWinnerClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(TradeWinnerClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        TradeWinnerClass->setStatusBar(statusBar);
        QWidget::setTabOrder(tbview_tasks, tabwid_holder);
        QWidget::setTabOrder(tabwid_holder, combox_sell_type);
        QWidget::setTabOrder(combox_sell_type, le_stock);
        QWidget::setTabOrder(le_stock, dbspbox_alert_price);
        QWidget::setTabOrder(dbspbox_alert_price, dbspbox_alert_percent);
        QWidget::setTabOrder(dbspbox_alert_percent, spinBox_continue_time);
        QWidget::setTabOrder(spinBox_continue_time, spinBox_quantity);
        QWidget::setTabOrder(spinBox_quantity, pbtn_all_quantity);
        QWidget::setTabOrder(pbtn_all_quantity, combox_price_level);
        QWidget::setTabOrder(combox_price_level, timeEdit_begin);
        QWidget::setTabOrder(timeEdit_begin, timeEdit_end);
        QWidget::setTabOrder(timeEdit_end, spinBox_retreat);
        QWidget::setTabOrder(spinBox_retreat, cb_back_alert_trigger);
        QWidget::setTabOrder(cb_back_alert_trigger, dbspbox_step_range);
        QWidget::setTabOrder(dbspbox_step_range, pbtn_add_task);
        QWidget::setTabOrder(pbtn_add_task, combox_buy_type);
        QWidget::setTabOrder(combox_buy_type, le_buytask_stock);
        QWidget::setTabOrder(le_buytask_stock, dbspbox_buytask_alert_price);
        QWidget::setTabOrder(dbspbox_buytask_alert_price, dbspbox_buytask_alert_percent);
        QWidget::setTabOrder(dbspbox_buytask_alert_percent, spinBox_buytask_continue_time);
        QWidget::setTabOrder(spinBox_buytask_continue_time, spinBox_buytask_quantity);
        QWidget::setTabOrder(spinBox_buytask_quantity, pbtn_buytask_all_quantity);
        QWidget::setTabOrder(pbtn_buytask_all_quantity, combox_bt_price_level);
        QWidget::setTabOrder(combox_bt_price_level, timeEdit_buytask_begin);
        QWidget::setTabOrder(timeEdit_buytask_begin, timeEdit_buytask_end);
        QWidget::setTabOrder(timeEdit_buytask_end, spinBox_bt_retreat);
        QWidget::setTabOrder(spinBox_bt_retreat, cb_bt_back_alert_trigger);
        QWidget::setTabOrder(cb_bt_back_alert_trigger, dbspbox_bt_step_range);
        QWidget::setTabOrder(dbspbox_bt_step_range, spinBox_buytask_times);
        QWidget::setTabOrder(spinBox_buytask_times, pbtn_add_buytask);
        QWidget::setTabOrder(pbtn_add_buytask, pte_log);
        QWidget::setTabOrder(pte_log, pte_capital);
        QWidget::setTabOrder(pte_capital, pbtn_query_capital);
        QWidget::setTabOrder(pbtn_query_capital, le_eqsec_stock);
        QWidget::setTabOrder(le_eqsec_stock, dbspbox_eqsec_start_price);
        QWidget::setTabOrder(dbspbox_eqsec_start_price, dbspbox_eqsec_raise_percent);
        QWidget::setTabOrder(dbspbox_eqsec_raise_percent, dbspbox_eqsec_fall_percent);
        QWidget::setTabOrder(dbspbox_eqsec_fall_percent, spinBox_eqsec_quantity);
        QWidget::setTabOrder(spinBox_eqsec_quantity, combox_eqsec_price_level);
        QWidget::setTabOrder(combox_eqsec_price_level, timeEdit_eqsec_begin);
        QWidget::setTabOrder(timeEdit_eqsec_begin, timeEdit_eqsec_end);
        QWidget::setTabOrder(timeEdit_eqsec_end, pbtn_add_eqsection_task);

        menuBar->addAction(menu_system->menuAction());
        menuBar->addAction(menu_operate->menuAction());
        menuBar->addAction(tool_menu->menuAction());
        menuBar->addAction(menu_help->menuAction());
        menu_system->addAction(actionClose);
        menu_system->addAction(actionRestart);
        menu_operate->addAction(actionStopAllTask);
        tool_menu->addAction(actionOpenCalcWin);

        retranslateUi(TradeWinnerClass);

        tabwid_holder->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(TradeWinnerClass);
    } // setupUi

    void retranslateUi(QMainWindow *TradeWinnerClass)
    {
        TradeWinnerClass->setWindowTitle(QApplication::translate("TradeWinnerClass", "TradeWinner 0.2 Copyright reserved by sparta.wwy", 0));
        actionClose->setText(QApplication::translate("TradeWinnerClass", "\351\200\200\345\207\272", 0));
        actionRestart->setText(QApplication::translate("TradeWinnerClass", "\351\207\215\346\226\260\345\220\257\345\212\250", 0));
        actionStopAllTask->setText(QApplication::translate("TradeWinnerClass", "\345\201\234\346\255\242\346\211\200\346\234\211\344\273\273\345\212\241", 0));
        actionOpenCalcWin->setText(QApplication::translate("TradeWinnerClass", "\350\256\241\347\256\227\345\231\250", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_task_list), QApplication::translate("TradeWinnerClass", "\344\273\273\345\212\241\345\210\227\350\241\250", 0));
        label_buytask_alert_price->setText(QApplication::translate("TradeWinnerClass", "\350\202\241\347\245\250\344\275\216\344\272\216:", 0));
        label_buytask_stock->setText(QApplication::translate("TradeWinnerClass", "\350\202\241\347\245\250\344\273\243\347\240\201:", 0));
        label_buytask_show_pic->setText(QApplication::translate("TradeWinnerClass", "TextLabel", 0));
        pbtn_add_buytask->setText(QApplication::translate("TradeWinnerClass", "\346\267\273\345\212\240\344\273\273\345\212\241", 0));
        cb_bt_back_alert_trigger->setText(QApplication::translate("TradeWinnerClass", "\345\233\236\345\275\222\350\247\246\345\217\221", 0));
        label_retreat_bfh_2->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_bt_retreat->setText(QApplication::translate("TradeWinnerClass", "\345\217\215\345\274\271\350\266\205\350\277\207:", 0));
        label_bt_step_range->setText(QApplication::translate("TradeWinnerClass", "\344\273\245\345\220\216\346\257\217\350\267\214:", 0));
        step_range_bfh_2->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_bt_times->setText(QApplication::translate("TradeWinnerClass", "\344\271\260\345\205\245\346\254\241\346\225\260:", 0));
        lab_buytask_quantity->setText(QApplication::translate("TradeWinnerClass", "\344\271\260\345\205\245\346\225\260\351\207\217:", 0));
        label_buytask_total_num->setText(QApplication::translate("TradeWinnerClass", "\344\271\260\345\205\245\346\225\260\351\207\217:", 0));
        label_buytask_monitor_time->setText(QApplication::translate("TradeWinnerClass", "\347\233\221\346\216\247\346\227\266\351\227\264:", 0));
        label_price_level_2->setText(QApplication::translate("TradeWinnerClass", "\344\272\244\346\230\223\344\273\267\346\240\274:", 0));
        label_21->setText(QApplication::translate("TradeWinnerClass", "---", 0));
        label_continue_time_2->setText(QApplication::translate("TradeWinnerClass", "\346\214\201\347\273\255:", 0));
        label_22->setText(QApplication::translate("TradeWinnerClass", "\347\247\222", 0));
        label_19->setText(QApplication::translate("TradeWinnerClass", "\346\234\200\345\244\247\345\217\257\344\271\260:", 0));
        pbtn_buytask_all_quantity->setText(QApplication::translate("TradeWinnerClass", "\345\205\250\351\203\250", 0));
        cb_buytask_chase_limitup->setText(QApplication::translate("TradeWinnerClass", "\350\277\275\346\266\250\345\201\234", 0));
        label_alert_bfh_2->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_buytask), QApplication::translate("TradeWinnerClass", "\344\271\260\345\205\245\344\273\273\345\212\241", 0));
        lab_out_sell2->setText(QApplication::translate("TradeWinnerClass", "sell2", 0));
        label_4->setText(QApplication::translate("TradeWinnerClass", "sell4", 0));
        label_5->setText(QApplication::translate("TradeWinnerClass", "sell5", 0));
        label_6->setText(QApplication::translate("TradeWinnerClass", "--------------------------------------", 0));
        lab_out_buy1->setText(QApplication::translate("TradeWinnerClass", "sell5", 0));
        label->setText(QApplication::translate("TradeWinnerClass", "sell1", 0));
        label_3->setText(QApplication::translate("TradeWinnerClass", "sell3", 0));
        label_2->setText(QApplication::translate("TradeWinnerClass", "sell2", 0));
        lab_out_buy3->setText(QApplication::translate("TradeWinnerClass", "sell3", 0));
        lab_out_buy5->setText(QApplication::translate("TradeWinnerClass", "sell1", 0));
        lab_out_sell4->setText(QApplication::translate("TradeWinnerClass", "sell4", 0));
        label_7->setText(QApplication::translate("TradeWinnerClass", "buy5", 0));
        label_11->setText(QApplication::translate("TradeWinnerClass", "buy2", 0));
        lab_out_sell1->setText(QApplication::translate("TradeWinnerClass", "sell1", 0));
        lab_out_sell3->setText(QApplication::translate("TradeWinnerClass", "sell3", 0));
        lab_out_buy4->setText(QApplication::translate("TradeWinnerClass", "sell2", 0));
        lab_out_sell5->setText(QApplication::translate("TradeWinnerClass", "sell5", 0));
        label_10->setText(QApplication::translate("TradeWinnerClass", "buy4", 0));
        lab_out_buy2->setText(QApplication::translate("TradeWinnerClass", "sell4", 0));
        label_8->setText(QApplication::translate("TradeWinnerClass", "buy1", 0));
        label_9->setText(QApplication::translate("TradeWinnerClass", "buy3", 0));
        cb_back_alert_trigger->setText(QApplication::translate("TradeWinnerClass", "\345\233\236\345\275\222\350\247\246\345\217\221", 0));
        label_retreat_bfh->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_retreat->setText(QApplication::translate("TradeWinnerClass", "\345\233\236\350\220\275\350\266\205\350\277\207:", 0));
        pbtn_add_task->setText(QApplication::translate("TradeWinnerClass", "\346\267\273\345\212\240\344\273\273\345\212\241", 0));
        label_stock->setText(QApplication::translate("TradeWinnerClass", "\350\202\241\347\245\250\344\273\243\347\240\201:", 0));
        label_alert_price->setText(QApplication::translate("TradeWinnerClass", "\350\202\241\347\245\250\344\275\216\344\272\216:", 0));
        label_alert_bfh->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_step_range->setText(QApplication::translate("TradeWinnerClass", "\351\230\266\346\242\257\345\271\205\345\272\246:", 0));
        step_range_bfh->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_monitor->setText(QApplication::translate("TradeWinnerClass", "\347\233\221\346\216\247\346\227\266\351\227\264:", 0));
        label_time_mid->setText(QApplication::translate("TradeWinnerClass", "---", 0));
        label_sell_num->setText(QApplication::translate("TradeWinnerClass", "\345\215\226\345\207\272\346\225\260\351\207\217:", 0));
        label_price_level->setText(QApplication::translate("TradeWinnerClass", "\344\272\244\346\230\223\344\273\267\346\240\274:", 0));
        label_total_num->setText(QApplication::translate("TradeWinnerClass", "\346\234\200\345\244\247\346\225\260\351\207\217", 0));
        label_pt_max_num->setText(QApplication::translate("TradeWinnerClass", "\346\234\200\345\244\247\345\215\226\345\207\272:", 0));
        pbtn_all_quantity->setText(QApplication::translate("TradeWinnerClass", "\345\205\250\351\203\250", 0));
        label_continue_sec->setText(QApplication::translate("TradeWinnerClass", "\347\247\222", 0));
        label_continue_time->setText(QApplication::translate("TradeWinnerClass", "\346\214\201\347\273\255:", 0));
        label_show_pic->setText(QApplication::translate("TradeWinnerClass", "TextLabel", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_sell_task), QApplication::translate("TradeWinnerClass", "\345\215\226\345\207\272\344\273\273\345\212\241", 0));
        label_buytask_stock_2->setText(QApplication::translate("TradeWinnerClass", "\350\202\241\347\245\250\344\273\243\347\240\201:", 0));
        label_eqsec_start_price->setText(QApplication::translate("TradeWinnerClass", "\350\265\267\345\247\213\344\273\267\346\240\274:", 0));
        label_raise_percent->setText(QApplication::translate("TradeWinnerClass", "\346\257\217\344\270\212\345\215\207:", 0));
        label_raise_percent_bfh->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_raise_percent_sell->setText(QApplication::translate("TradeWinnerClass", "\345\215\226\345\207\272", 0));
        label_raise_percent_bfh_2->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_fall_percent->setText(QApplication::translate("TradeWinnerClass", "\346\257\217\344\270\213\351\231\215:", 0));
        label_raise_percent_buy->setText(QApplication::translate("TradeWinnerClass", "\344\271\260\345\205\245", 0));
        label_price_level_3->setText(QApplication::translate("TradeWinnerClass", "\344\272\244\346\230\223\344\273\267\346\240\274:", 0));
        label_buytask_monitor_time_2->setText(QApplication::translate("TradeWinnerClass", "\347\233\221\346\216\247\346\227\266\351\227\264:", 0));
        label_23->setText(QApplication::translate("TradeWinnerClass", "---", 0));
        lab_eqsec_quantity->setText(QApplication::translate("TradeWinnerClass", "\344\271\260\345\215\226\346\225\260\351\207\217:", 0));
        pbtn_add_eqsection_task->setText(QApplication::translate("TradeWinnerClass", "\346\267\273\345\212\240\344\273\273\345\212\241", 0));
        label_eqsec_maxprice->setText(QApplication::translate("TradeWinnerClass", "\347\240\264\351\241\266\345\201\234\346\255\242\344\273\267\346\240\274:", 0));
        label_eqsec_maxprice_2->setText(QApplication::translate("TradeWinnerClass", "\347\240\264\345\272\225\346\270\205\344\273\223\344\273\267\346\240\274:", 0));
        cb_min_clear_trigger->setText(QString());
        cb_max_stop_trigger->setText(QString());
        lab_max_quantity->setText(QApplication::translate("TradeWinnerClass", "\346\234\200\345\244\247\344\273\223\344\275\215:", 0));
        cb_max_qty->setText(QString());
        lab_min_quantity->setText(QApplication::translate("TradeWinnerClass", "\345\272\225\344\273\223\346\225\260\351\207\217:", 0));
        cb_min_qty->setText(QString());
        cb_eqsec_back_trigger->setText(QApplication::translate("TradeWinnerClass", "\345\233\236\345\275\222\350\247\246\345\217\221", 0));
        label_eqsec_percent->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        label_eqsec_rebounce->setText(QApplication::translate("TradeWinnerClass", "\346\213\220\347\202\271:", 0));
        cb_eqsec_rebounce->setText(QApplication::translate("TradeWinnerClass", "\345\220\257\347\224\250\346\213\220\347\202\271", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_eq_section_trd), QApplication::translate("TradeWinnerClass", "\345\214\272\351\227\264\344\272\244\346\230\223", 0));
        label_bktest_adv_reb->setText(QApplication::translate("TradeWinnerClass", "\346\213\220\347\202\271:", 0));
        label_raise_percent_rebounce_2->setText(QApplication::translate("TradeWinnerClass", "%", 0));
        lab_bktest_adv_secnums->setText(QApplication::translate("TradeWinnerClass", "\345\214\272\351\227\264\346\225\260:", 0));
        lab_bktest_advsec_qty->setText(QApplication::translate("TradeWinnerClass", "\345\215\225\345\214\272\351\227\264\350\202\241\346\225\260:", 0));
        label_bktest_maxprice_adv->setText(QApplication::translate("TradeWinnerClass", "\351\241\266\351\203\250\344\273\267\346\240\274:", 0));
        label_bktest_maxprice_5->setText(QApplication::translate("TradeWinnerClass", "\346\270\205\344\273\223\344\273\267\346\240\274:", 0));
        lab_bktest_start_capital_2->setText(QApplication::translate("TradeWinnerClass", "\346\273\241\344\273\223\350\265\204\351\207\221:", 0));
        label_buytask_stock_bktest->setText(QApplication::translate("TradeWinnerClass", "\350\202\241\347\245\250\344\273\243\347\240\201:", 0));
        pbtn_add_adveq_task->setText(QApplication::translate("TradeWinnerClass", "\346\267\273\345\212\240\344\273\273\345\212\241", 0));
        label_24->setText(QApplication::translate("TradeWinnerClass", "---", 0));
        label_buytask_monitor_time_3->setText(QApplication::translate("TradeWinnerClass", "\347\233\221\346\216\247\346\227\266\351\227\264:", 0));
        label_price_level_5->setText(QApplication::translate("TradeWinnerClass", "\344\272\244\346\230\223\344\273\267\346\240\274:", 0));
        pbtn_adveq_need_capital->setText(QApplication::translate("TradeWinnerClass", "\350\256\241\347\256\227\346\273\241\344\273\223\350\265\204\351\207\221", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_advsec_task), QApplication::translate("TradeWinnerClass", "\350\264\235\345\241\224\345\214\272\351\227\264", 0));
        pbtn_query_capital->setText(QApplication::translate("TradeWinnerClass", "\346\237\245\350\257\242", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_capital), QApplication::translate("TradeWinnerClass", "\350\265\204\344\272\247\344\277\241\346\201\257", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_log), QApplication::translate("TradeWinnerClass", "\346\227\245\345\277\227\350\256\260\345\275\225", 0));
        label_index_kind->setText(QApplication::translate("TradeWinnerClass", "\346\214\207\346\225\260\347\261\273\345\210\253:", 0));
        grp_relstock_trade->setTitle(QString());
        label_sell_num_2->setText(QApplication::translate("TradeWinnerClass", "\345\215\226\345\207\272\346\225\260\351\207\217:", 0));
        label_stock_3->setText(QApplication::translate("TradeWinnerClass", "\350\202\241\347\245\250\344\273\243\347\240\201:", 0));
        label_price_level_4->setText(QApplication::translate("TradeWinnerClass", "\344\272\244\346\230\223\344\273\267\346\240\274:", 0));
        grp_choice_bs->setTitle(QString());
        radioBtn_sell->setText(QApplication::translate("TradeWinnerClass", "\345\215\226\345\207\272", 0));
        radioBtn_buy->setText(QApplication::translate("TradeWinnerClass", "\344\271\260\345\205\245", 0));
        grp_updownkind->setTitle(QString());
        radiobtn_cross_down->setText(QApplication::translate("TradeWinnerClass", "\344\270\213\347\251\277", 0));
        radiobtn_cross_up->setText(QApplication::translate("TradeWinnerClass", "\344\270\212\347\251\277", 0));
        label_index_pos->setText(QApplication::translate("TradeWinnerClass", "\346\214\207\346\225\260\347\202\271\344\275\215:", 0));
        groupBox_kind_choice->setTitle(QString());
        radiobtn_clearall->setText(QApplication::translate("TradeWinnerClass", "\346\270\205\344\273\223", 0));
        radiobtn_reltrade->setText(QApplication::translate("TradeWinnerClass", "\345\205\263\350\201\224\344\272\244\346\230\223", 0));
        radiobtn_alert->setText(QApplication::translate("TradeWinnerClass", "\351\242\204\350\255\246", 0));
        pbtn_add_indtrd_task->setText(QApplication::translate("TradeWinnerClass", "\346\267\273\345\212\240\344\273\273\345\212\241", 0));
        label_index_continue_sec->setText(QApplication::translate("TradeWinnerClass", "\347\247\222", 0));
        label_index_continue_time->setText(QApplication::translate("TradeWinnerClass", "\346\214\201\347\273\255:", 0));
        label_time_mid_2->setText(QApplication::translate("TradeWinnerClass", "---", 0));
        label_monitor_2->setText(QApplication::translate("TradeWinnerClass", "\347\233\221\346\216\247\346\227\266\351\227\264:", 0));
        tabwid_holder->setTabText(tabwid_holder->indexOf(tab_stkindex_task), QApplication::translate("TradeWinnerClass", "\346\214\207\346\225\260\351\243\216\346\216\247", 0));
        menu_system->setTitle(QApplication::translate("TradeWinnerClass", "\347\263\273\347\273\237", 0));
        menu_help->setTitle(QApplication::translate("TradeWinnerClass", "\345\270\256\345\212\251", 0));
        menu_operate->setTitle(QApplication::translate("TradeWinnerClass", "\346\223\215\344\275\234", 0));
        tool_menu->setTitle(QApplication::translate("TradeWinnerClass", "\345\267\245\345\205\267", 0));
    } // retranslateUi

};

namespace Ui {
    class TradeWinnerClass: public Ui_TradeWinnerClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_TRADE_WINNER_H
